# Generated by Django 5.2.3 on 2025-06-17 13:44

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=user.utils.user_directory_path),
        ),
    ]
