# Generated by Django 5.2.3 on 2025-06-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_location_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
    ]
