# Generated by Django 5.2.3 on 2025-06-18 13:23

import django.core.validators
import django.utils.timezone
import localflavor.in_.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_location_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN code', regex='^\\d{6}$')], verbose_name='pin code'),
            preserve_default=False,
        ),
    ]
